
#pragma once

#define CONST_MAX_LENGTH 128
#define CONST_HASH_PRIME 1099511628211ULL
#define CONST_HASH_OFFSET_BASIS 14695981039346656037ULL

#define const_hash_func(s, n, i, x) ((x ^ s[i < n ? n - 1 - i : 0]) * CONST_HASH_PRIME)

#define const_hash_impl_128(s, n, x) x
#define const_hash_impl_127(s, n, x) ((127 < n) ? const_hash_func(s, n, 127, const_hash_impl_128(s, n, x)) : x)
#define const_hash_impl_126(s, n, x) ((126 < n) ? const_hash_func(s, n, 126, const_hash_impl_127(s, n, x)) : x)
#define const_hash_impl_125(s, n, x) ((125 < n) ? const_hash_func(s, n, 125, const_hash_impl_126(s, n, x)) : x)
#define const_hash_impl_124(s, n, x) ((124 < n) ? const_hash_func(s, n, 124, const_hash_impl_125(s, n, x)) : x)
#define const_hash_impl_123(s, n, x) ((123 < n) ? const_hash_func(s, n, 123, const_hash_impl_124(s, n, x)) : x)
#define const_hash_impl_122(s, n, x) ((122 < n) ? const_hash_func(s, n, 122, const_hash_impl_123(s, n, x)) : x)
#define const_hash_impl_121(s, n, x) ((121 < n) ? const_hash_func(s, n, 121, const_hash_impl_122(s, n, x)) : x)
#define const_hash_impl_120(s, n, x) ((120 < n) ? const_hash_func(s, n, 120, const_hash_impl_121(s, n, x)) : x)
#define const_hash_impl_119(s, n, x) ((119 < n) ? const_hash_func(s, n, 119, const_hash_impl_120(s, n, x)) : x)
#define const_hash_impl_118(s, n, x) ((118 < n) ? const_hash_func(s, n, 118, const_hash_impl_119(s, n, x)) : x)
#define const_hash_impl_117(s, n, x) ((117 < n) ? const_hash_func(s, n, 117, const_hash_impl_118(s, n, x)) : x)
#define const_hash_impl_116(s, n, x) ((116 < n) ? const_hash_func(s, n, 116, const_hash_impl_117(s, n, x)) : x)
#define const_hash_impl_115(s, n, x) ((115 < n) ? const_hash_func(s, n, 115, const_hash_impl_116(s, n, x)) : x)
#define const_hash_impl_114(s, n, x) ((114 < n) ? const_hash_func(s, n, 114, const_hash_impl_115(s, n, x)) : x)
#define const_hash_impl_113(s, n, x) ((113 < n) ? const_hash_func(s, n, 113, const_hash_impl_114(s, n, x)) : x)
#define const_hash_impl_112(s, n, x) ((112 < n) ? const_hash_func(s, n, 112, const_hash_impl_113(s, n, x)) : x)
#define const_hash_impl_111(s, n, x) ((111 < n) ? const_hash_func(s, n, 111, const_hash_impl_112(s, n, x)) : x)
#define const_hash_impl_110(s, n, x) ((110 < n) ? const_hash_func(s, n, 110, const_hash_impl_111(s, n, x)) : x)
#define const_hash_impl_109(s, n, x) ((109 < n) ? const_hash_func(s, n, 109, const_hash_impl_110(s, n, x)) : x)
#define const_hash_impl_108(s, n, x) ((108 < n) ? const_hash_func(s, n, 108, const_hash_impl_109(s, n, x)) : x)
#define const_hash_impl_107(s, n, x) ((107 < n) ? const_hash_func(s, n, 107, const_hash_impl_108(s, n, x)) : x)
#define const_hash_impl_106(s, n, x) ((106 < n) ? const_hash_func(s, n, 106, const_hash_impl_107(s, n, x)) : x)
#define const_hash_impl_105(s, n, x) ((105 < n) ? const_hash_func(s, n, 105, const_hash_impl_106(s, n, x)) : x)
#define const_hash_impl_104(s, n, x) ((104 < n) ? const_hash_func(s, n, 104, const_hash_impl_105(s, n, x)) : x)
#define const_hash_impl_103(s, n, x) ((103 < n) ? const_hash_func(s, n, 103, const_hash_impl_104(s, n, x)) : x)
#define const_hash_impl_102(s, n, x) ((102 < n) ? const_hash_func(s, n, 102, const_hash_impl_103(s, n, x)) : x)
#define const_hash_impl_101(s, n, x) ((101 < n) ? const_hash_func(s, n, 101, const_hash_impl_102(s, n, x)) : x)
#define const_hash_impl_100(s, n, x) ((100 < n) ? const_hash_func(s, n, 100, const_hash_impl_101(s, n, x)) : x)
#define const_hash_impl_99(s, n, x) ((99 < n) ? const_hash_func(s, n, 99, const_hash_impl_100(s, n, x)) : x)
#define const_hash_impl_98(s, n, x) ((98 < n) ? const_hash_func(s, n, 98, const_hash_impl_99(s, n, x)) : x)
#define const_hash_impl_97(s, n, x) ((97 < n) ? const_hash_func(s, n, 97, const_hash_impl_98(s, n, x)) : x)
#define const_hash_impl_96(s, n, x) ((96 < n) ? const_hash_func(s, n, 96, const_hash_impl_97(s, n, x)) : x)
#define const_hash_impl_95(s, n, x) ((95 < n) ? const_hash_func(s, n, 95, const_hash_impl_96(s, n, x)) : x)
#define const_hash_impl_94(s, n, x) ((94 < n) ? const_hash_func(s, n, 94, const_hash_impl_95(s, n, x)) : x)
#define const_hash_impl_93(s, n, x) ((93 < n) ? const_hash_func(s, n, 93, const_hash_impl_94(s, n, x)) : x)
#define const_hash_impl_92(s, n, x) ((92 < n) ? const_hash_func(s, n, 92, const_hash_impl_93(s, n, x)) : x)
#define const_hash_impl_91(s, n, x) ((91 < n) ? const_hash_func(s, n, 91, const_hash_impl_92(s, n, x)) : x)
#define const_hash_impl_90(s, n, x) ((90 < n) ? const_hash_func(s, n, 90, const_hash_impl_91(s, n, x)) : x)
#define const_hash_impl_89(s, n, x) ((89 < n) ? const_hash_func(s, n, 89, const_hash_impl_90(s, n, x)) : x)
#define const_hash_impl_88(s, n, x) ((88 < n) ? const_hash_func(s, n, 88, const_hash_impl_89(s, n, x)) : x)
#define const_hash_impl_87(s, n, x) ((87 < n) ? const_hash_func(s, n, 87, const_hash_impl_88(s, n, x)) : x)
#define const_hash_impl_86(s, n, x) ((86 < n) ? const_hash_func(s, n, 86, const_hash_impl_87(s, n, x)) : x)
#define const_hash_impl_85(s, n, x) ((85 < n) ? const_hash_func(s, n, 85, const_hash_impl_86(s, n, x)) : x)
#define const_hash_impl_84(s, n, x) ((84 < n) ? const_hash_func(s, n, 84, const_hash_impl_85(s, n, x)) : x)
#define const_hash_impl_83(s, n, x) ((83 < n) ? const_hash_func(s, n, 83, const_hash_impl_84(s, n, x)) : x)
#define const_hash_impl_82(s, n, x) ((82 < n) ? const_hash_func(s, n, 82, const_hash_impl_83(s, n, x)) : x)
#define const_hash_impl_81(s, n, x) ((81 < n) ? const_hash_func(s, n, 81, const_hash_impl_82(s, n, x)) : x)
#define const_hash_impl_80(s, n, x) ((80 < n) ? const_hash_func(s, n, 80, const_hash_impl_81(s, n, x)) : x)
#define const_hash_impl_79(s, n, x) ((79 < n) ? const_hash_func(s, n, 79, const_hash_impl_80(s, n, x)) : x)
#define const_hash_impl_78(s, n, x) ((78 < n) ? const_hash_func(s, n, 78, const_hash_impl_79(s, n, x)) : x)
#define const_hash_impl_77(s, n, x) ((77 < n) ? const_hash_func(s, n, 77, const_hash_impl_78(s, n, x)) : x)
#define const_hash_impl_76(s, n, x) ((76 < n) ? const_hash_func(s, n, 76, const_hash_impl_77(s, n, x)) : x)
#define const_hash_impl_75(s, n, x) ((75 < n) ? const_hash_func(s, n, 75, const_hash_impl_76(s, n, x)) : x)
#define const_hash_impl_74(s, n, x) ((74 < n) ? const_hash_func(s, n, 74, const_hash_impl_75(s, n, x)) : x)
#define const_hash_impl_73(s, n, x) ((73 < n) ? const_hash_func(s, n, 73, const_hash_impl_74(s, n, x)) : x)
#define const_hash_impl_72(s, n, x) ((72 < n) ? const_hash_func(s, n, 72, const_hash_impl_73(s, n, x)) : x)
#define const_hash_impl_71(s, n, x) ((71 < n) ? const_hash_func(s, n, 71, const_hash_impl_72(s, n, x)) : x)
#define const_hash_impl_70(s, n, x) ((70 < n) ? const_hash_func(s, n, 70, const_hash_impl_71(s, n, x)) : x)
#define const_hash_impl_69(s, n, x) ((69 < n) ? const_hash_func(s, n, 69, const_hash_impl_70(s, n, x)) : x)
#define const_hash_impl_68(s, n, x) ((68 < n) ? const_hash_func(s, n, 68, const_hash_impl_69(s, n, x)) : x)
#define const_hash_impl_67(s, n, x) ((67 < n) ? const_hash_func(s, n, 67, const_hash_impl_68(s, n, x)) : x)
#define const_hash_impl_66(s, n, x) ((66 < n) ? const_hash_func(s, n, 66, const_hash_impl_67(s, n, x)) : x)
#define const_hash_impl_65(s, n, x) ((65 < n) ? const_hash_func(s, n, 65, const_hash_impl_66(s, n, x)) : x)
#define const_hash_impl_64(s, n, x) ((64 < n) ? const_hash_func(s, n, 64, const_hash_impl_65(s, n, x)) : x)
#define const_hash_impl_63(s, n, x) ((63 < n) ? const_hash_func(s, n, 63, const_hash_impl_64(s, n, x)) : x)
#define const_hash_impl_62(s, n, x) ((62 < n) ? const_hash_func(s, n, 62, const_hash_impl_63(s, n, x)) : x)
#define const_hash_impl_61(s, n, x) ((61 < n) ? const_hash_func(s, n, 61, const_hash_impl_62(s, n, x)) : x)
#define const_hash_impl_60(s, n, x) ((60 < n) ? const_hash_func(s, n, 60, const_hash_impl_61(s, n, x)) : x)
#define const_hash_impl_59(s, n, x) ((59 < n) ? const_hash_func(s, n, 59, const_hash_impl_60(s, n, x)) : x)
#define const_hash_impl_58(s, n, x) ((58 < n) ? const_hash_func(s, n, 58, const_hash_impl_59(s, n, x)) : x)
#define const_hash_impl_57(s, n, x) ((57 < n) ? const_hash_func(s, n, 57, const_hash_impl_58(s, n, x)) : x)
#define const_hash_impl_56(s, n, x) ((56 < n) ? const_hash_func(s, n, 56, const_hash_impl_57(s, n, x)) : x)
#define const_hash_impl_55(s, n, x) ((55 < n) ? const_hash_func(s, n, 55, const_hash_impl_56(s, n, x)) : x)
#define const_hash_impl_54(s, n, x) ((54 < n) ? const_hash_func(s, n, 54, const_hash_impl_55(s, n, x)) : x)
#define const_hash_impl_53(s, n, x) ((53 < n) ? const_hash_func(s, n, 53, const_hash_impl_54(s, n, x)) : x)
#define const_hash_impl_52(s, n, x) ((52 < n) ? const_hash_func(s, n, 52, const_hash_impl_53(s, n, x)) : x)
#define const_hash_impl_51(s, n, x) ((51 < n) ? const_hash_func(s, n, 51, const_hash_impl_52(s, n, x)) : x)
#define const_hash_impl_50(s, n, x) ((50 < n) ? const_hash_func(s, n, 50, const_hash_impl_51(s, n, x)) : x)
#define const_hash_impl_49(s, n, x) ((49 < n) ? const_hash_func(s, n, 49, const_hash_impl_50(s, n, x)) : x)
#define const_hash_impl_48(s, n, x) ((48 < n) ? const_hash_func(s, n, 48, const_hash_impl_49(s, n, x)) : x)
#define const_hash_impl_47(s, n, x) ((47 < n) ? const_hash_func(s, n, 47, const_hash_impl_48(s, n, x)) : x)
#define const_hash_impl_46(s, n, x) ((46 < n) ? const_hash_func(s, n, 46, const_hash_impl_47(s, n, x)) : x)
#define const_hash_impl_45(s, n, x) ((45 < n) ? const_hash_func(s, n, 45, const_hash_impl_46(s, n, x)) : x)
#define const_hash_impl_44(s, n, x) ((44 < n) ? const_hash_func(s, n, 44, const_hash_impl_45(s, n, x)) : x)
#define const_hash_impl_43(s, n, x) ((43 < n) ? const_hash_func(s, n, 43, const_hash_impl_44(s, n, x)) : x)
#define const_hash_impl_42(s, n, x) ((42 < n) ? const_hash_func(s, n, 42, const_hash_impl_43(s, n, x)) : x)
#define const_hash_impl_41(s, n, x) ((41 < n) ? const_hash_func(s, n, 41, const_hash_impl_42(s, n, x)) : x)
#define const_hash_impl_40(s, n, x) ((40 < n) ? const_hash_func(s, n, 40, const_hash_impl_41(s, n, x)) : x)
#define const_hash_impl_39(s, n, x) ((39 < n) ? const_hash_func(s, n, 39, const_hash_impl_40(s, n, x)) : x)
#define const_hash_impl_38(s, n, x) ((38 < n) ? const_hash_func(s, n, 38, const_hash_impl_39(s, n, x)) : x)
#define const_hash_impl_37(s, n, x) ((37 < n) ? const_hash_func(s, n, 37, const_hash_impl_38(s, n, x)) : x)
#define const_hash_impl_36(s, n, x) ((36 < n) ? const_hash_func(s, n, 36, const_hash_impl_37(s, n, x)) : x)
#define const_hash_impl_35(s, n, x) ((35 < n) ? const_hash_func(s, n, 35, const_hash_impl_36(s, n, x)) : x)
#define const_hash_impl_34(s, n, x) ((34 < n) ? const_hash_func(s, n, 34, const_hash_impl_35(s, n, x)) : x)
#define const_hash_impl_33(s, n, x) ((33 < n) ? const_hash_func(s, n, 33, const_hash_impl_34(s, n, x)) : x)
#define const_hash_impl_32(s, n, x) ((32 < n) ? const_hash_func(s, n, 32, const_hash_impl_33(s, n, x)) : x)
#define const_hash_impl_31(s, n, x) ((31 < n) ? const_hash_func(s, n, 31, const_hash_impl_32(s, n, x)) : x)
#define const_hash_impl_30(s, n, x) ((30 < n) ? const_hash_func(s, n, 30, const_hash_impl_31(s, n, x)) : x)
#define const_hash_impl_29(s, n, x) ((29 < n) ? const_hash_func(s, n, 29, const_hash_impl_30(s, n, x)) : x)
#define const_hash_impl_28(s, n, x) ((28 < n) ? const_hash_func(s, n, 28, const_hash_impl_29(s, n, x)) : x)
#define const_hash_impl_27(s, n, x) ((27 < n) ? const_hash_func(s, n, 27, const_hash_impl_28(s, n, x)) : x)
#define const_hash_impl_26(s, n, x) ((26 < n) ? const_hash_func(s, n, 26, const_hash_impl_27(s, n, x)) : x)
#define const_hash_impl_25(s, n, x) ((25 < n) ? const_hash_func(s, n, 25, const_hash_impl_26(s, n, x)) : x)
#define const_hash_impl_24(s, n, x) ((24 < n) ? const_hash_func(s, n, 24, const_hash_impl_25(s, n, x)) : x)
#define const_hash_impl_23(s, n, x) ((23 < n) ? const_hash_func(s, n, 23, const_hash_impl_24(s, n, x)) : x)
#define const_hash_impl_22(s, n, x) ((22 < n) ? const_hash_func(s, n, 22, const_hash_impl_23(s, n, x)) : x)
#define const_hash_impl_21(s, n, x) ((21 < n) ? const_hash_func(s, n, 21, const_hash_impl_22(s, n, x)) : x)
#define const_hash_impl_20(s, n, x) ((20 < n) ? const_hash_func(s, n, 20, const_hash_impl_21(s, n, x)) : x)
#define const_hash_impl_19(s, n, x) ((19 < n) ? const_hash_func(s, n, 19, const_hash_impl_20(s, n, x)) : x)
#define const_hash_impl_18(s, n, x) ((18 < n) ? const_hash_func(s, n, 18, const_hash_impl_19(s, n, x)) : x)
#define const_hash_impl_17(s, n, x) ((17 < n) ? const_hash_func(s, n, 17, const_hash_impl_18(s, n, x)) : x)
#define const_hash_impl_16(s, n, x) ((16 < n) ? const_hash_func(s, n, 16, const_hash_impl_17(s, n, x)) : x)
#define const_hash_impl_15(s, n, x) ((15 < n) ? const_hash_func(s, n, 15, const_hash_impl_16(s, n, x)) : x)
#define const_hash_impl_14(s, n, x) ((14 < n) ? const_hash_func(s, n, 14, const_hash_impl_15(s, n, x)) : x)
#define const_hash_impl_13(s, n, x) ((13 < n) ? const_hash_func(s, n, 13, const_hash_impl_14(s, n, x)) : x)
#define const_hash_impl_12(s, n, x) ((12 < n) ? const_hash_func(s, n, 12, const_hash_impl_13(s, n, x)) : x)
#define const_hash_impl_11(s, n, x) ((11 < n) ? const_hash_func(s, n, 11, const_hash_impl_12(s, n, x)) : x)
#define const_hash_impl_10(s, n, x) ((10 < n) ? const_hash_func(s, n, 10, const_hash_impl_11(s, n, x)) : x)
#define const_hash_impl_9(s, n, x) ((9 < n) ? const_hash_func(s, n, 9, const_hash_impl_10(s, n, x)) : x)
#define const_hash_impl_8(s, n, x) ((8 < n) ? const_hash_func(s, n, 8, const_hash_impl_9(s, n, x)) : x)
#define const_hash_impl_7(s, n, x) ((7 < n) ? const_hash_func(s, n, 7, const_hash_impl_8(s, n, x)) : x)
#define const_hash_impl_6(s, n, x) ((6 < n) ? const_hash_func(s, n, 6, const_hash_impl_7(s, n, x)) : x)
#define const_hash_impl_5(s, n, x) ((5 < n) ? const_hash_func(s, n, 5, const_hash_impl_6(s, n, x)) : x)
#define const_hash_impl_4(s, n, x) ((4 < n) ? const_hash_func(s, n, 4, const_hash_impl_5(s, n, x)) : x)
#define const_hash_impl_3(s, n, x) ((3 < n) ? const_hash_func(s, n, 3, const_hash_impl_4(s, n, x)) : x)
#define const_hash_impl_2(s, n, x) ((2 < n) ? const_hash_func(s, n, 2, const_hash_impl_3(s, n, x)) : x)
#define const_hash_impl_1(s, n, x) ((1 < n) ? const_hash_func(s, n, 1, const_hash_impl_2(s, n, x)) : x)
#define const_hash_impl_0(s, n, x) ((0 < n) ? const_hash_func(s, n, 0, const_hash_impl_1(s, n, x)) : x)

#define const_hash(s) const_hash_impl_0(s, sizeof(s) - 1, CONST_HASH_OFFSET_BASIS)

//! EOF

